import = [
    "~/.config/alacritty/themes/themes/citylights.toml"
    # "~/.config/alacritty/themes/themes/flat_remix.toml"
    # "~/.config/alacritty/themes/themes/github_dark_tritanopia.toml"
    # "~/.config/alacritty/themes/themes/tomorrow_night_bright.toml"
    # "~/.config/alacritty/themes/themes/xterm.toml"
]


[env]
TERM = "xterm-256color"

[window]
padding.x = 10
padding.y = 10
startup_mode = "Maximized"
decorations = "Buttonless"
opacity = 0.9
blur = true
option_as_alt = "OnlyLeft"

[font]
normal.family = "MesloLGSDZ Nerd Font"
size = 13
