---
- hosts: all
  name: Provision dev server
  tasks:
    - block:
        - name: Include variables from a file
          include_vars: macos/variables.yml

        - name: Include macOS setup
          include_tasks: macos/tasks/sudoers.yml
          when: configure_sudoers
          tags: ['sudoers']

        - name: Include macOS setup
          include_tasks: macos/tasks/osx.yml
          when: configure_osx
          tags: ['osx']

        - name: Include macOS roles
          include_role:
            name: "{{ item }}"
          loop:
            - elliotweiser.osx-command-line-tools
            - geerlingguy.mac.homebrew
            - geerlingguy.mac.dock
      when: ansible_os_family == "Darwin"

    - name: Include Debian setup
      include_tasks: debian/setup-debian.yml
      when: ansible_os_family == "Debian"

    - name: Include rust role
      include_role:
        name: rust
      when: ansible_os_family == "Debian"

    - name: Include base role
      include_role:
        name: debian/roles/base
      when: ansible_os_family == "Debian"

    - name: Include yarn role
      include_role:
        name: roles/yarn
      when: ansible_os_family == "Debian"

    - name: Include nvm role
      include_role:
        name: nvm

    - name: Include rbenv role
      include_role:
        name: rbenv

    - name: Include ohmyzsh role
      include_role:
        name: ohmyzsh

    - name: Include dotfiles role
      include_role:
        name: dotfiles

    - name: Include neovim role
      include_role:
        name: neovim
