- name: Install zsh
  become: true
  apt:
    name: zsh
  when: ansible_os_family == "Debian"

- name: Install pexpect
  become: true
  apt:
    name: python3-pexpect
  when: ansible_os_family == "Debian"

- name: Clone OhmyZsh
  git:
    repo: https://github.com/robbyrussell/oh-my-zsh.git 
    dest: ~/.oh-my-zsh
    accept_hostkey: yes

- name: Clone fish like autosuggestions
  git:
    repo: https://github.com/zsh-users/zsh-autosuggestions
    dest: ~/.oh-my-zsh/custom/plugins/zsh-autosuggestions
    accept_hostkey: yes

- name: Clone fish like syntax highlighting
  git:
    repo: https://github.com/zsh-users/zsh-syntax-highlighting.git
    dest: ~/.oh-my-zsh/custom/plugins/zsh-syntax-highlighting
    accept_hostkey: yes

- name: Default shell
  expect:
    command: "chsh -s /bin/zsh"
    responses:
      (?i)password:
        - "{{ user_password }}"
    creates: ".shell_is_zsh"
  when: ansible_os_family == "Debian"
